# **Librería numérica de *Python*: *NumPy***
---
<img src = "https://raw.githubusercontent.com/numpy/numpy/master/branding/logo/primary/numpylogo.png" alt = "NumPy logo" width = "70%">  </img>


*NumPy* (del inglés ***Numerical Python***) es la librería fundamental para la computación científica con *Python*. 
Contiene funcionalidades de:

* Análisis Numérico.
* Álgebra lineal y matricial.
* Probabilidad y estadística.
* Números aleatorios.
* Otras herramientas matemáticas.

Además de su uso científico, *NumPy* provee una estructura de datos adicional llamada **arreglo**. Un arreglo es un contenedor multidimensional eficiente para datos genéricos. Los arreglos son especialmente útiles en el manejo de grandes volúmenes de datos. Además, estos contenedores se pueden definir con tipos de datos arbitrarios, lo que permite a *NumPy* integrarse de manera rápida y sin problemas con una amplia variedad de bases de datos.

*NumPy* también permite un alto rendimiento y mejor optimización de la memoria por sus rutinas implementadas en lenguaje C, que por su naturaleza compilada es más eficiente y cercano al sistema operativo, ideal para esta tarea.


## **1. Importar *NumPy***
---

*NumPy* viene instalado por defecto en la mayoría de las distribuciones de *Python*, en especial en aquellas orientadas a la computación científica. Una vez *NumPy* esté instalado, se puede importar como una librería para su ejecución en código de *Python*. Esto se puede hacer de las siguientes maneras:



**1.1. Importar *NumPy* con el alias `np`**: Es una práctica común en la comunidad de desarrolladores importar *NumPy* con el alias **`np`** en sus llamados en código, y es incluso utilizado de esta forma en su [documentación oficial](https://numpy.org/devdocs/user/quickstart.html). Esta va a ser la forma utilizada en el desarrollo de este tutorial y materiales futuros.

In [1]:
import numpy as np

In [2]:
np.array(None)

array(None, dtype=object)

**1.2. Importando *NumPy* sin alias:** Esta alternativa funciona de igual forma que la anterior, pero utilizando **`numpy`** en vez de **`np`** cuando se haga el llamado en código.

In [3]:
import numpy

In [4]:
numpy.array(None)

array(None, dtype=object)

**1.3. Importando los métodos de *NumPy*:** Si se hace de esta manera se puede llamar las funciones y atributos de *NumPy* de manera directa. Por ejemplo:

In [5]:
#El símbolo * indica a Python que importe todos los métodos y atributos de NumPy
from numpy import *     

In [6]:
#Se pueden importar por separado los elementos con comas (,).
from numpy import array, arange   

In [7]:
array(None)

array(None, dtype=object)

Este material se realizó con las siguientes versiones:
*  *Python*: 3.6.9
*  *NumPy*:  1.19.5

In [8]:
#Versión de Python y NumPy
!python --version
print('NumPy', np.__version__)

Python 3.9.7
NumPy 1.20.3


## **2. ndarray - Arreglos de _NumPy_**
---

Los arreglos son el objeto principal de *NumPy* y en torno a ellos gira toda su funcionalidad. Un arreglo es una colección ordenada de elementos del mismo tipo, como las listas, pero con longitud inmutable. Esto quiere decir que los elementos de cada posición de un arreglo se pueden modificar, a diferencia de las tuplas, pero su longitud no se puede modificar sin crear un objeto nuevo.

Los arreglos de *NumPy* pueden representar:
  * **Vectores**. (Arreglos de 1 dimensión)
  * **Matrices**. (Arreglos de 2 dimensiones) 
  * **Tensores**. (Arreglos de 3 dimensiones en adelante) 


Generalmente se recomienda usar arreglos de *NumPy* en vez de listas genéricas de Python. A pesar de ser conceptualmente similares, elegir entre listas y arreglos es una decisión de diseño importante al considerar el desempeño y uso de memoria de un programa. Para conocer más información acerca de por qué usar arreglos en lugar de listas, lo invitamos a consultar [este post de StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

### **2.1. Creación de arreglos**
---

Existen múltiples formas para crear arreglos de *NumPy*. Para crear arreglos a partir de datos ordenados preexistentes, como tuplas o listas de *Python*, se utiliza la función **`np.array`** que recibe como parámetro el objeto original y genera un objeto **`numpy.ndarray`**. Este es el nombre del tipo de dato de los arreglos de *NumPy*.

In [9]:
# Con listas
lista = [1, 2, 3]
np.array(lista)

array([1, 2, 3])

**Observación**: A continuación se usa un control de warnings para evitar mensaes al ejecutar una linea de código, ver [Warning control](https://docs.python.org/3/library/warnings.html#) para más información

In [16]:
np.warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning) 

# Con tuplas
tupla = (1, [1,2,3], 3)
np.array(tupla)

array([1, list([1, 2, 3]), 3], dtype=object)

In [17]:
# Con la combinación de tuplas y listas anidadas. Esto genera arreglos de 2 o más dimensiones.
matriz = ([1, 2, 3], (4, 5, 6), [7, 8, 9])
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Los elementos que contienen los arreglos deben ser uniformes y homogéneos con respecto a un tipo de dato único. Cuando no se especifica, *NumPy* infiere el tipo de dato apropiado para los datos de entrada. Los tipos de datos soportados por *NumPy* se denominan en su notación como **`dtype`** y se pueden pasar como argumento en la creación de arreglos en la mayoría de funciones. 
A continuación, se presentan algunos de los nombres usados para los tipos de datos genéricos, con su equivalente en *Python*:

| *Numpy* dtype             | *Python* type |
|---------------------------|---------------|
| number, inexact, floating | float         |
| complexfloating           | cfloat        |
| integer, signedinteger    | int_          |
| unsignedinteger           | uint          |
| character                 | string        |
| generic, flexible         | void          |


Esta es una lista de algunos de los *dtype* numéricos soportados en *NumPy* con su equivalente en el lenguaje de programación C, más cercano a la máquina y en general más eficiente por su naturaleza.

| *Numpy* dtype               | C type              |
|-----------------------------|---------------------|
| np.bool_                    | bool                |
| np.byte                     | signed char         |
| np.ubyte                    | unsigned char       |
| np.short                    | short               |
| np.ushort                   | unsigned short      |
| np.intc                     | int                 |
| np.uintc                    | unsigned int        |
| np.int_                     | long                |
| np.uint                     | unsigned long       |
| np.longlong                 | long long           |
| np.ulonglong                | unsigned long long  |
| np.half / np.float16        | float               |
| np.single                   | float               |
| np.double                   | double              |
| np.longdouble               | long double         |
| np.csingle                  | float complex       |
| np.cdouble                  | double complex      |
| np.clongdouble              | long double complex |
| np.int8                     | int8_t              |
| np.int16                    | int16_t             |
| np.int32                    | int32_t             |
| np.int64                    | int64_t             |
| np.uint8                    | uint8_t             |
| np.uint16                   | uint16_t            |
| np.uint32                   | uint32_t            |
| np.uint64                   | uint64_t            |
| np.intp                     | intptr_t            |
| np.uintp                    | uintptr_t           |
| np.float32                  | float               |
| np.float64 / np.float_      | double              |
| np.complex64                | float complex       |
| np.complex128 / np.complex_ | double complex      |

Además de estos tipos se consideran otros tipos de dato no numéricos especiales:

* **`np.nan`**: Sigla del inglés *not a number*. Este tipo de dato se le otorga a los elementos de un arreglo numérico que no pueden ser interpretados como un resultado numérico. Se usa por lo general para indicar la presencia de valores faltantes o que deberían ser ignorados. Para arreglos no numéricos esto se hace con el tipo **`None`** de *Python*.

* **`np.object`**: *NumPy* admite el uso de los tipos de datos genéricos de *Python*. **`numpy.object`** es el tipo genérico para cualquier dato que no corresponda con estas primitivas. Esta regla aplica para listas, conjuntos, entre otros.



Para más información, consulte la [entrada de la documentación oficial](https://numpy.org/devdocs/reference/arrays.dtypes.html) referente a los tipos de dato **`dtype`**.

In [18]:
np.array(['051.2', '027.0', '233.7'], dtype = np.float64)

array([ 51.2,  27. , 233.7])

In [19]:
# NumPy también admite la especificación de dtypes con cadenas de texto

np.array(['001', '002', '003'], dtype = "int") 

array([1, 2, 3])

Además de la función **`np.array()`**, *NumPy* dispone de varias funciones para generar arreglos comunes. A continuación se presentan algunos de los más importantes:

*  **`np.arange(inicio, final, paso, dtype)`**: Este método es el análogo de la función **`range`** de *Python* para la creación de arreglos. Admite un argumento *dtype* para definir el tipo de dato del arreglo generado.

In [20]:
np.arange(0, 50, 5, dtype = 'complex')

array([ 0.+0.j,  5.+0.j, 10.+0.j, 15.+0.j, 20.+0.j, 25.+0.j, 30.+0.j,
       35.+0.j, 40.+0.j, 45.+0.j])

*  **`np.empty(shape, dtype)`**: Este método permite generar arreglos "vacíos" con las dimensiones de **shape**. El argumento *shape* puede ser de varias dimensiones, definido como una tupla **(n, m)**, de tamaño **n** (filas) por **m** (columnas). Estos arreglos se consideran vacíos de forma conceptual, pero esto no es del todo correcto.

 Al realizar el llamado de la función, *NumPy* reserva el espacio de memoria para el arreglo, pero no inicializa sus casillas con un elemento específico. Es por esto que estos arreglos pueden tener elementos "basura" de ejecuciones pasadas.

In [21]:
np.empty((500,200))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
# Para arreglos de una dimensión:
np.empty(5, dtype = 'int')

array([ 94842709507184,               0,  94842709508192, 140455133204592,
       140455167715568])

*  **`np.full(shape, a, dtype)`**: Este método permite crear un arreglo en el que todos los elementos tengan el valor inicial **`a`**.

In [27]:
np.full((10, 5), "z")

array([['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z'],
       ['z', 'z', 'z', 'z', 'z']], dtype='<U1')

In [28]:
# Para arreglos de una dimensión:
np.full(10, 100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

*  **`np.ones((n, m))`**: Este método funciona de la misma manera que **`np.full`** con uno como valor inicial. 

In [29]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# Para arreglos de una dimensión:
np.ones(10, dtype = 'int') # Puede ser necesario definir el tipo del arreglo durante su creación.

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

*  **`np.zeros((n, m))`**: Este método funciona de la misma manera que **`np.full`** con cero como valor inicial.

In [31]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
# Para arreglos de una dimensión:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

*  **`np.eye(n, m)`**: Este método genera una matriz o arreglo de 2 dimensiones en el que la diagonal principal está compuesta de unos y el resto de la matriz está compuesta de unos. Si el argumento **`m`** no es pasado se genera una matriz cuadrada de tamaño $n$ por $n$.

In [33]:
np.eye(10, dtype= 'int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [34]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

*  **`np.linspace(inicio, final, tamaño, endpoint)`**: Este método permite generar **`tamaño`** elementos desde **`inicio`** hasta **`final`** separados uniformemente en una escala lineal. Puede producir el mismo resultado que cuando se usa **`np.arange`** y se desconoce el tamaño del paso necesario para producir la misma cantidad de elementos. Al contrario que con **`np.arange`** el final está contenido en el arreglo generado a menos que se indique lo contrario con el argumento booleano opcional **`endpoint`**.

In [35]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
# Equivalente a np.arange(0, 2, 0.2)
np.linspace(0, 2, 10, endpoint = False)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

*  **`np.logspace(inicio, final, tamaño, endpoint, base)`**: Este método es equivalente al método **`np.linspace`** pero generando elementos separados en una escala logarítmica. Esto quiere decir que se generan elementos linealmente que corresponden al exponente de cada elemento del arreglo resultante. La base de esa potencia está definida por defecto en 10, pero puede cambiarse con el argumento **`base`** de la función.

In [37]:
np.logspace(0, 4, 5, dtype = float)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04])

In [38]:
np.logspace(0, 5, 6, base = 2, dtype = int)

array([ 1,  2,  4,  8, 16, 32])

### **2.2 Atributos de arreglos**
---

Cada objeto de *NumPy* tiene algunos atributos que son de gran utilidad para su identificación y entendimiento. A continuación se presentan algunos de los más importantes.

*  **`arr.dtype`**: Este atributo permite conocer el **`dtype`** que tiene el arreglo.

In [39]:
arr = np.array([1.5, 0, 3.2])
arr.dtype

dtype('float64')

In [40]:
arr = np.empty(15, dtype= np.bool_)
arr.dtype

dtype('bool')


*  **`arr.shape`**: Este atributo permite conocer las dimensiones de un arreglo. Estas dimensiones están contenidas en una tupla y por lo tanto se pueden desempaquetar en variables distintas.

In [41]:
arr = np.zeros((3,2,4)) # Arreglo de 3 dimensiones
arr.shape

(3, 2, 4)

In [42]:
n, m, w = arr.shape
print(n)
print(m)
print(w)

3
2
4


*  **`arr.ndim`**: Este atributo permite conocer el número de dimensiones de un arreglo. Esto es equivalente a verificar el tamaño de la tupla retornada por **`arr.shape`**.

In [43]:
arr = np.ones((2,2,2,2,2))
arr.ndim

5


*  **`arr.size`**: Este atributo permite conocer el número de elementos o casillas disponibles en un arreglo.

In [44]:
arr = np.empty((3,3))
arr.size

9

In [45]:
# El tamaño no se ve afectado si alguno de los elementos es NaN o None.
arr = np.array([1, np.NaN, 2, np.NaN, None])
arr.size

5


*  **`arr.itemsize`**: Este atributo permite conocer el tamaño en *bytes* que ocupa cada elemento de un arreglo. Como los elementos tienen que ser homogéneos este tamaño es el máximo de sus elementos contenidos.

In [46]:
arr = np.eye(100)
arr.itemsize

8

In [47]:
# Podemos calcular la cantidad de bytes reservada para el arreglo completo en memoria
arr.itemsize * arr.size

80000

In [48]:
lista = [1, True, 'Cadena de texto larga']

arr = np.array(lista)
arr.itemsize

84


*  **`arr.real` y `arr.imag`**: Estos atributos permiten conocer la parte real  e imaginaria de un objeto de números complejos. Estas partes son arreglos completos generados a partir del arreglo original con *dtype float*.

In [49]:
arr = np.full((5,3), 5 + 10j)
arr

array([[5.+10.j, 5.+10.j, 5.+10.j],
       [5.+10.j, 5.+10.j, 5.+10.j],
       [5.+10.j, 5.+10.j, 5.+10.j],
       [5.+10.j, 5.+10.j, 5.+10.j],
       [5.+10.j, 5.+10.j, 5.+10.j]])

In [50]:
arr.real

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [51]:
arr.imag

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [52]:
# Los arreglos retornados pueden ser tratados como arreglos normales, con sus atributos y métodos.
arr.imag.dtype

dtype('float64')


*  **`arr.T`**: Esto atributo permite generar la matriz transpuesta de un arreglo. La transpuesta de una matriz es aquella cuyas filas corresponden a las columnas de la original.

In [53]:
arr = np.eye(5,3)

arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
arr.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [55]:
arr = np.zeros((2,4))

print(arr.shape)
print(arr.T.shape)

(2, 4)
(4, 2)


## **3. np.random - Números aleatorios**
---

*NumPy* dispone del módulo **`numpy.random`** que cuenta con una gran variedad de funciones para la generación de números aleatorios a partir de distribuciones de probabilidad, que se verán en detalle en la unidad 3.

El estudio de algoritmos para la generación de números aleatorios es un campo en sí mismo de las ciencias de la computación. En la práctica, los números aleatorios generados por computador son pseudo-aleatorios y dependen de una semilla inicial sobre la cual se realizan cálculos precisos en colecciones de números aparentemente aleatorios. 

*NumPy* permite definir esta semilla para garantizar la reproducibilidad de los experimentos aleatorios. Esto se consigue con la función **`np.random.seed(semilla)`** de la siguiente forma:

In [56]:
np.random.seed(12345) # Semilla seleccionada arbitrariamente, podría ser otro número entero.

Con la semilla definida, las operaciones realizadas por el módulo **`random`** de *NumPy* van a generar el mismo resultado, con una distribución aleatoria. En este material no se profundizará en las virtudes de *NumPy* en la generación de números aleatorios, sino que se presentarán las funciones más comunes. Estas son:

*  **`np.random.rand(shape)`**: Genera números aleatorios distribuidos uniformemente entre 0 y 1. El argumento **`shape`** permite definir las dimensiones del arreglo de números aleatorios independientes. Si este argumento no es pasado a la función, se genera un único número aleatorio. 
> *En una distribución uniforme todos los números reales entre 0 y 1 tienen la misma probabilidad de ocurrencia.*

In [57]:
np.random.rand()  

0.9296160928171479

In [58]:
# Si se ejecuta otra vez, retorna un número distinto
np.random.rand()

0.3163755545817859

In [59]:
np.random.rand(5)

array([0.18391881, 0.20456028, 0.56772503, 0.5955447 , 0.96451452])

In [60]:
np.random.rand(9,3)

array([[0.6531771 , 0.74890664, 0.65356987],
       [0.74771481, 0.96130674, 0.0083883 ],
       [0.10644438, 0.29870371, 0.65641118],
       [0.80981255, 0.87217591, 0.9646476 ],
       [0.72368535, 0.64247533, 0.71745362],
       [0.46759901, 0.32558468, 0.43964461],
       [0.72968908, 0.99401459, 0.67687371],
       [0.79082252, 0.17091426, 0.02684928],
       [0.80037024, 0.90372254, 0.02467621]])

*  **`np.random.randn(shape)`**: Genera números aleatorios generados a partir de una distribución normal estándar, centrada en $0$ y con una desviación estándar de $1$. Las distribuciones de probabilidad se discutirán en las unidades **2** y **3**.

In [61]:
np.random.randn()

3.248943919430755

In [62]:
np.random.randn(2,3)

array([[-1.02122752e+00, -5.77087303e-01,  1.24121276e-01],
       [ 3.02613562e-01,  5.23772068e-01,  9.40277775e-04]])


*  **`np.random.randint(inicio, final, shape)`**: 
Genera números enteros aleatorios desde el primer parámetro (incluido) hasta el segundo parámetro (excluido). Si se pasa un tercer argumento, éste será las dimensiones que tendrá el arreglo de enteros aleatorios retornado.

In [63]:
np.random.randint(1,100) 

51

In [64]:
np.random.randint(90,100,(3,4))

array([[92, 99, 97, 95],
       [97, 91, 90, 99],
       [93, 90, 93, 90]])

## **4. Indexado de arreglos**

Los elementos de los arreglos de NumPy se pueden consultar y modificar de la misma forma que las listas de *Python*, con la sintaxis de llaves cuadradas `[` y `]`. Las reglas definidas para rangos, intervalos con paso definido y el uso de números negativos para el indexado desde el final también aplican en los arreglos de *NumPy*.

In [65]:
arr = np.arange(0, 100)

In [66]:
arr[0]

0

In [67]:
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[0:15:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [69]:
arr[-1]

99

In [70]:
arr[-5:]

array([95, 96, 97, 98, 99])

Para arreglos multidimensionales se define una forma especial de obtener los elementos de un arreglo, que difiere del método usado en las listas de *Python* de llaves consecutivas. Para indexar elementos multidimensionales en *NumPy* es suficiente con separar las expresiones de indexado de cada dimensión con comas. 

Si no se ingresan expresiones suficientes para indexar todas las dimensiones del arreglo se interpreta como indexado completo para las últimas dimensiones, retornando todos los elementos.

In [71]:
arr = np.array([[1,3],[2,8]])
arr

array([[1, 3],
       [2, 8]])

In [72]:
#Obtener el elemento de la primera fila y primera columna
arr[0,0]

1

In [73]:
#Obtener el elemento de la última fila y última columna
arr[-1,-1]

8

In [74]:
#Obtener todos los elementos de la primera fila
arr[0,:]

array([1, 3])

In [75]:
#Reasignar todos los elementos de la primera columna
arr[:,0] = [-100, 25]
arr

array([[-100,    3],
       [  25,    8]])

In [76]:
# Ejemplo de inicialización manual

n = 5
m = 5
arr2d = np.zeros((n,m))
for i in range(n):
  for j in range(m):
    arr2d[i, j] = (i + 1)* (j + 1)
    
arr2d

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  4.,  6.,  8., 10.],
       [ 3.,  6.,  9., 12., 15.],
       [ 4.,  8., 12., 16., 20.],
       [ 5., 10., 15., 20., 25.]])

In [77]:
# Seleccionar la matriz 2x2 de la esquina inferior derecha
arr2d[3:,3:]

array([[16., 20.],
       [20., 25.]])

Para arreglos de dimensiones superiores se permite el formato general **`arr_nd[d1][d2]...[dn]`** o **`arr_2d[d1,d2,...,dn]`**. 

Por claridad y debido al comportamiento del indexado, se recomienda usar siempre la notación con coma.

In [78]:
# Creación de un arreglo de 3 dimensiones o tensor.
# Se puede entender como un arreglo de matrices.
arr_3d = np.array(([[[5, 10], [20, 25]], [[7, 21], [7, 28]]]))
arr_3d

array([[[ 5, 10],
        [20, 25]],

       [[ 7, 21],
        [ 7, 28]]])

In [79]:
# Accediendo a un elemento particular
arr_3d[0, 0, 0]

5

In [80]:
# Tomar el primer elemento de la primera dimensión 
# (Es decir, la primera matriz)
arr_3d[0,:,:]


array([[ 5, 10],
       [20, 25]])

In [81]:
# Traer la primera fila de las 2 submatrices
arr_3d[:,0,:]

array([[ 5, 10],
       [ 7, 21]])

In [82]:
# Traer la última fila de las 2 submatrices
arr_3d[:,-1,:]

array([[20, 25],
       [ 7, 28]])

Además del indexado natural presentado hasta el momento, los arreglos de *NumPy* aceptan colecciones de enteros que representan las filas o columnas que se desean retornar por cada dimensión. Esto se conoce como *fancy indexing* o indexado elegante.

In [83]:
arr = np.arange(100,121)
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120])

In [84]:
# Obtener elementos también en cualquier orden
# Los elementos de la lista corresponden a los índices a los cuales se quiere acceder, en ese orden
arr[[7, 3, 4, 2]] 

array([107, 103, 104, 102])

In [85]:
# Inicialización de una matriz con comprensión de listas
n = 8
m = 8
arr2d = np.array([[i]*n for i in range(m)])
  
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [86]:
# Obtener elementos de la matriz en cualquier orden
arr2d[[6,4,2],:]

array([[6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2]])

In [87]:
arr2d = np.eye(8)

arr2d[:,[1,4,2,7]]

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [88]:
np.eye(4)[:, [0,2,1,3]] #Matriz identidad con dos columnas cambiadas.

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

Existe un método de indexado adicional que se realiza por medio de condiciones lógicas. Este es el método de selección condicional o *boolean masking* mediante el cual se aceptan arreglos de booleanos para definir los valores accedidos en la expresión.

Esto ocurre en dos pasos:

1. Se aplica un operador lógico en un arreglo y un valor escalar. Esta operación retorna un arreglo de booleanos.
   > **Nota:** Las operaciones en arreglos se verán en detalle más adelante en este material.

2. El arreglo producido en el paso anterior es ingresado como el índice del arreglo. De esta forma se accede a los elementos que cumplieran la condición lógica definida con el operador del primer paso.


Veamos un ejemplo paso por paso:

In [91]:
# Se crea un arreglo
A = np.array([[ 1, -4,  3, -3],
              [-4, -2, -1,  1],
              [ 0,  1,  2, -2],
              [-5, -3, -4,  4]])

A

array([[ 1, -4,  3, -3],
       [-4, -2, -1,  1],
       [ 0,  1,  2, -2],
       [-5, -3, -4,  4]])

In [92]:
# Operador lógico
# Esta expresión evalúa por cada elemento del arreglo
# si este es mayor que 0.

A > 0

array([[ True, False,  True, False],
       [False, False, False,  True],
       [False,  True,  True, False],
       [False, False, False,  True]])

In [93]:
# Se usa la expresión anterior directamente en el arreglo
# Si las dimensiones no permiten crear una matriz, se retorna un arreglo plano.
A[A < 0] 

array([-4, -3, -4, -2, -1, -2, -5, -3, -4])

In [95]:
# Se asigna el valor escalar 0 a cada elemento del arreglo original.
A[A < 0] = 0

A

array([[1, 0, 3, 0],
       [0, 0, 0, 1],
       [0, 1, 2, 0],
       [0, 0, 0, 4]])

Usando condiciones compuestas:

In [97]:
#Usando condiciones más complejas
A[(A>1) & (A<4)] = 50 

A

array([[ 1,  0, 50,  0],
       [ 0,  0,  0,  1],
       [ 0,  1, 50,  0],
       [ 0,  0,  0,  4]])

Nótese que en este caso se utiliza el operador **`&`** (*bitwise and*) y no el operador lógico **`and`**. En el caso de una "or" lógica, el operador correcto en este caso sería **`|`** en lugar de **`or`**. Por último, la negación se obtiene con **`~`** en vez de **`not`**. Veamos algunos ejemplos:

In [98]:
A[(A>=50) |(A==0)] = 2 
A

array([[1, 2, 2, 2],
       [2, 2, 2, 1],
       [2, 1, 2, 2],
       [2, 2, 2, 4]])

In [99]:
A[~(A<3)] = 100 
A

array([[  1,   2,   2,   2],
       [  2,   2,   2,   1],
       [  2,   1,   2,   2],
       [  2,   2,   2, 100]])

## **5. Operaciones en arreglos**
---

*NumPy* dispone de múltiples funciones y rutinas de uso general en la computación científica. Estas pueden ser invocadas como el método de un arreglo o con alto nivel tomando arreglos como parámetro. 

### **5.1. Operadores en arreglos**
---

Los mismos operadores utilizados entre variables de tipos de dato primitivos en *Python* pueden usarse entre arreglos, siempre y cuando los tipos de dato que contienen permitan o tengan una semántica propia para la operación.

 A continuación se listan algunas de las operaciones numéricas y lógicas que se pueden realizar entre arreglos.

* **Suma `+` | `np.add(a,b)`**: La suma entre arreglos está definida como la suma de matrices en álgebra lineal, dando como resultado la suma elemento a elemento de cada combinación de filas y columnas. Además, *NumPy* tiene una propiedad especial llamada *broadcasting*, que permite operar arreglos de tamaños distintos de forma dinámica, ampliando con su repetición al arreglo más pequeño para ajustarse a la capacidad necesaria para permitir la operación. Esto solo es posible si ambos operandos comparten el mismo tamaño de una dimensión.

In [100]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [101]:
a

array([1, 2, 3])

In [102]:
b

array([10, 20, 30])

In [103]:
a + b

array([11, 22, 33])

In [104]:
np.add(a,b)

array([11, 22, 33])

In [105]:
c = np.full((6, 3), 100)

c

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [106]:
#Los arreglos a y b se expanden repitiendo sus filas para la operación (broadcasting)
c + a + b

array([[111, 122, 133],
       [111, 122, 133],
       [111, 122, 133],
       [111, 122, 133],
       [111, 122, 133],
       [111, 122, 133]])

Este comportamiento se diferencia al de las listas de *Python*. Con las listas, este operador sirve para concatenar los elementos de dos listas. En *NumPy* se operan los elementos de ambos arreglos. Para concatenar arreglos de *NumPy*, consulte la sección $5.4$ de este material.

In [107]:
ls_a = [1, 2, 3]
ls_b = [4, 5, 6]

ls_a, ls_b

([1, 2, 3], [4, 5, 6])

In [108]:
arr_a = np.array(ls_a)
arr_b = np.array(ls_b)

arr_a, arr_b

(array([1, 2, 3]), array([4, 5, 6]))

In [109]:
# Operando listas (Concatenación)
ls_a + ls_b

[1, 2, 3, 4, 5, 6]

In [110]:
# Operando arreglos (Suma elemento a elemento)
arr_a + arr_b

array([5, 7, 9])

In [111]:
# Si al menos uno de los elementos es un arreglo, NumPy se encarga de
# realizar la conversión respectiva (cast).
# Arreglo + lista
arr_a + ls_b

array([5, 7, 9])

* **Resta `-` | `np.subtract(a,b)`**: Al igual que la suma, la resta entre arreglos está definida como su operación homóloga en matrices, dando como resultado la resta elemento a elemento de cada combinación de filas y columnas.

In [112]:
a = np.ones((3,3))
b = np.eye(3)

a - b

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [113]:
np.subtract(a, b)

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [114]:
c = np.full((7,3), 10)
d = np.ones(3)

c - d

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

* **Multiplicación `*` | `np.multiply(a, b)`**: La multiplicación entre arreglos de *NumPy* con el operador **`*`** no corresponde a la definición de multiplicación de matrices de álgebra lineal. En su lugar, el resultado se comporta de la misma manera que la suma o la resta, multiplicando los elementos correspondientes por cada elemento de cada pareja de fila y columna. Gracias a esto es posible hacer *broadcasting* con la multiplicación. Otra propiedad del *broadcasting* es que se pueden operar arreglos con valores escalares, que sí actúan como la multiplicación por escalares definida en el álgebra matricial.

In [115]:
a = np.eye(3) * 5 # Multiplicación por escalar.
a

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [116]:
b = np.random.randint(0, 10, (3,3))
b

array([[6, 2, 1],
       [5, 8, 6],
       [5, 1, 0]])

In [117]:
a * b  # Multiplicación elemento a elemento

array([[30.,  0.,  0.],
       [ 0., 40.,  0.],
       [ 0.,  0.,  0.]])

In [118]:
np.multiply(a, b)

array([[30.,  0.,  0.],
       [ 0., 40.,  0.],
       [ 0.,  0.,  0.]])

Al igual que con el operador `+`, el comportamiento obtenido con el operador `*` se diferencia al de las listas de *Python*. Con las listas, ese operador sirve para repetir los elementos de una lista y requiere que uno de los operandos sea un entero. En *NumPy* se operan los elementos de ambos arreglos.

In [119]:
ls_a = [1, 2, 3]
ls_b = [10, 20, 30]

ls_a

[1, 2, 3]

In [120]:
arr_a = np.array(ls_a)
arr_b = np.array(ls_b)

arr_a, arr_b

(array([1, 2, 3]), array([10, 20, 30]))

In [121]:
# La multiplicación entre listas no está permitida.
#ls_a * ls_b # Si se descomenta esta sentencia saldrá un error

In [122]:
# Operando listas con un escalar (Repetición)
ls_b * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [123]:
# Operando arreglos con un escalar (Multiplicación escalar)
arr_a * 3

array([3, 6, 9])

In [124]:
# Sí se puede operar entre arreglos (Multiplicación elemento a elemento)
arr_a * arr_b

array([10, 40, 90])

In [125]:
# Si al menos uno de los elementos es un arreglo, NumPy se encarga de
# realizar el casteo respectivo.

arr_a * ls_b

array([10, 40, 90])

* **División `/` | `np.divide(a, b)`**: La división entre arreglos de *NumPy* con el operador `/` funciona de igual forma que las operaciones anteriores, dividiendo los elementos correspondientes por cada pareja de fila y columna.

In [126]:
a = np.random.randint(0, 10, (3,3))
a

array([[5, 8, 2],
       [9, 4, 7],
       [9, 5, 2]])

In [127]:
b  = np.ones((3,3)) * 10
b

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [128]:
a / b

array([[0.5, 0.8, 0.2],
       [0.9, 0.4, 0.7],
       [0.9, 0.5, 0.2]])

In [129]:
np.divide(a, b)

array([[0.5, 0.8, 0.2],
       [0.9, 0.4, 0.7],
       [0.9, 0.5, 0.2]])

In [130]:
a / 10 # Operación equivalente con escalares

array([[0.5, 0.8, 0.2],
       [0.9, 0.4, 0.7],
       [0.9, 0.5, 0.2]])

Cuando se trata con divisiones que involucran un 0 en el denominador el resultado es:
* **`NaN`** si ambos valores son $0$.
* **`inf`** (infinito positivo) si el numerador es positivo.
* **`-inf`** (infinito negativo) si el numerador es negativo.

In [131]:
# Retorna un warning al detectar este tipo de operaciones

a = np.array([1, 0, -1])
a / np.zeros(3)

/tmp/ipykernel_880646/2662674978.py:4: RuntimeWarning: divide by zero encountered in true_divide
  a / np.zeros(3)
/tmp/ipykernel_880646/2662674978.py:4: RuntimeWarning: invalid value encountered in true_divide
  a / np.zeros(3)


array([ inf,  nan, -inf])

* **Multiplicación matricial `@` | `np.matmul(a, b)`**: *NumPy* ofrece la posibilidad de ejecutar operaciones de álgebra lineal como la multiplicación de matrices. En este caso, se usa el operador **`@`**.

In [134]:
a = np.eye(4)
b = np.random.rand(4,3)

a @ b

array([[0.44399019, 0.75089204, 0.65789833],
       [0.36069729, 0.37832298, 0.64963192],
       [0.05563683, 0.07825928, 0.09190299],
       [0.80510503, 0.06530746, 0.22431937]])

In [135]:
# La ultima dimensión del primero deben coincidir o se produce un error
#b @ a # Si se descomenta esta sentencia saldrá un error

In [136]:
np.matmul(a, b)

array([[0.44399019, 0.75089204, 0.65789833],
       [0.36069729, 0.37832298, 0.64963192],
       [0.05563683, 0.07825928, 0.09190299],
       [0.80510503, 0.06530746, 0.22431937]])

* **Producto punto `np.dot(a, b)`**: Producto punto entre dos arreglos:
  * Si **`a`** y **`b`** son arreglos unidimensionales, se calcula el producto interno entre los vectores.
  * Si **`a`** y **`b`** son arreglos de 2 dimensiones (matrices), se calcula la multiplicación matricial, es decir, es equivalente a usar **`np.matmul`** o  **`a @ b`**.
  * Si alguno de los parámetros **`a`** o **`b`** es un escalar, se calcula la multiplicación entre un arreglo y un escalar como al usar **`multiply(a, b)`** o **`a * b`**.

In [137]:
a = np.ones((2,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [138]:
b = np.random.randint(0, 5, 5)
b

array([1, 2, 3, 0, 0])

In [139]:
np.dot(a, b)

array([6., 6.])

### **5.2. Cálculos sobre arreglos**
---
*NumPy* cuenta con un gran número de funciones de uso general usadas frecuentemente en áreas como la estadística o la geometría. Algunos de los cálculos directos posibles con funciones de *NumPy* son:


*  **`arr.max()`|`arr.min()`**: Para los arreglos con tipos de dato con un orden definido, como las cadenas de texto (orden alfanumérico) y los valores numéricos, *NumPy* permite ejecutar este método para calcular el valor mínimo o máximo del arreglo.

In [140]:
arr = np.random.randint(-20, 20, 30)
arr

array([ 15, -15,   4,  -6,  -1,   4,  10,  -8,  -9,  16,   5,   5,  12,
        13,   8, -14,  12,  -7,  17,   3,  -8,  -2,   9, -19,   5, -20,
         6,  -8,   6,   3])

In [141]:
arr.min()

-20

In [142]:
arr.max()

17

In [143]:
#Ambas funciones tienen un equivalente de alto nivel
#que también sirve para otro tipo de objetos

np.min(arr), np.max(arr)

(-20, 17)


*  **`arr.argmax()`|`arr.argmin()`**: En ocasiones es necesario encontrar la **posición** del elemento que es el máximo o mínimo de un arreglo. Esto es posible con los métodos **`argmax`** y **`argmin`**, respectivamente.

In [144]:
arr = np.array([0,1,2,3,4,5,6,7])

In [145]:
(arr.argmin(), arr.argmax())

(0, 7)

*  **Operaciones de agregación `arr.sum()`|`arr.prod()`**: Las operaciones de agregación son aquellas en las que se realiza un cálculo que puede involucrar a todos los elementos del arreglo, como la suma o el producto de todos sus elementos. Estas dos últimas operaciones comunes son posibles con los métodos **`arr.sum()`** y **`arr.prod()`**.

In [146]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
arr.sum()

45

In [148]:
arr.prod()

362880

In [149]:
#Equivalentes de alto nivel

(np.sum(arr), np.prod(arr))

(45, 362880)

*  **Operaciones acumuladas `arr.cumsum()`|`arr.cumprod()`**: Existen escenarios en los que se desea realizar una agregación, pero conservar los valores de cada punto o paso de la operación. 

  Para la suma y el producto, se consideran los métodos **`arr.cumsum()`** y **`arr.cumprod()`**.

In [150]:
arr = np.arange(1, 8)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [151]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

In [152]:
arr.cumprod()

array([   1,    2,    6,   24,  120,  720, 5040])

In [153]:
#Equivalentes de alto nivel
np.array([np.cumsum(arr), np.cumprod(arr)])

array([[   1,    3,    6,   10,   15,   21,   28],
       [   1,    2,    6,   24,  120,  720, 5040]])

*  **Funciones estadísticas `arr.mean()`|`arr.std()` | `arr.var()`**: *NumPy* permite realizar cálculos estadísticos básicos, como la media aritmética, la desviación estándar y la varianza. Estas estadísticas descriptivas y otras más se discutirán en la **Unidad 2** con la librería *pandas*. 

In [154]:
arr = np.random.randn(500)

In [155]:
arr.mean()

-0.013901534269583639

In [156]:
arr.std()

0.9911944829276211

In [157]:
arr.var()

0.9824665029861542

In [158]:
#Equivalentes de alto nivel
(np.mean(arr), np.std(arr), np.var(arr))

(-0.013901534269583639, 0.9911944829276211, 0.9824665029861542)

*  **Funciones universales**: Además de las operaciones discutidas, *NumPy* dispone de múltiples funciones comunes que pueden ser aplicadas directamente sobre arreglos de números. Estas no están disponibles como métodos de arreglos, y deben ser usadas con funciones de alto nivel. A continuación se presenta una lista de las funciones más importantes:

* **Operaciones matemáticas**
  * **`np.negative(x)`:** Negativo numérico.
  * **`np.positive(x)`:** Positivo numérico.
  * **`np.absolute(x)`:** Valor absoluto.
  * **`np.sign(x)`:** Signo numérico (-1, 0 o 1).  
  * **`np.exp(x)`:** Exponencial ($e^{x_i}$).
  * **`np.exp2(x)`:** Exponencial base 2 ($2^{x_i}$).
  * **`np.log(x)`:** Logaritmo natural ($\ln {x_i}$).
  * **`np.log2(x)`:** Logaritmo base 2 ($\log_{2}{x_i}$).
  * **`np.log10(x)`:** Logaritmo natural ($\log_{10}{x_i}$).
  * **`np.sqrt(x)`:** Raíz cuadrada ($\sqrt{x_i}$).
  * **`np.cbrt(x)`:** Raíz cúbica ($\sqrt[3]{x_i}$).
  * **`np.square(x)`:** Cuadrado del arreglo (${x_i}^2$).


* **Otras operaciones entre arreglos numéricos**
  * **`np.maximum(a,b)`:** Máximo entre elementos de dos arreglos. (elemento a elemento)
  * **`np.minimum(a,b)`:** Mínimo entre elementos de dos arreglos. (elemento a elemento)
  * **`np.power(a, b)`:** Potencia de arreglos ${a_i}^{b_i}$(elemento a elemento).
  * **`np.remainder(a, b)`|`np.mod(a, b)`:** Residuo de la división (elemento a elemento).
  * **`np.divmod(a, b)`:** Cociente y residuo (elemento a elemento).
  * **`np.gcd(a, b)`:** Máximo común divisor (elemento a elemento).
  * **`np.lcm(a, b)`:** Mínimo común múltiplo (elemento a elemento).

* **Funciones trigonométricas**
  * **`np.sin(x)`:** Seno trigonométrico.
  * **`np.cos(x)`:** Coseno trigonométrico.
  * **`np.tan(x)`:** Tangente trigonométrica.
  * **`np.arcsin(x)`:** Seno inverso trigonométrico.
  * **`np.arccos(x)`:** Coseno inverso trigonométrico.
  * **`np.arctan(x)`:** Tangente inversa trigonométrica.
  * **`np.sing(x)`:** Seno hiperbólico.
  * **`np.cosh(x)`:** Coseno hiperbólico.
  * **`np.tanh(x)`:** Tangente hiperbólica.
  * **`np.deg2rad(x)` | `np.radians(x)`:** Conversión de grados a radianes.
  * **`np.rad2deg(x)` | `np.degrees(x)`:** Conversión de radianes a grados.

* **Operaciones en números decimales**
  * **`np.isfinite(x)`**: Evaluación lógica de números finitos.
  * **`np.isinf(x)`**: Evaluación lógica de números infinitos.
  * **`np.isnan(x)`**: Evaluación lógica de valores NaN.
  * **`np.floor(x)`**: Función *piso*.
  * **`np.ceil(x)`**: Función *techo*.
  * **`np.trunc(x)`**: Valores truncados.


Puede consultar la lista completa en este [enlace](http://docs.scipy.org/doc/numpy/reference/ufuncs.html).



### **5.3. Transformación de arreglos**
---
*NumPy* provee métodos especializados para la transformación del contenido de los arreglos. En la mayoría de los casos, se generan arreglos nuevos a partir del arreglo original. Algunos de los más importantes son:

* **Añadir y eliminar elementos:** Dado que los arreglos en *NumPy* son inmutables en cuanto a tamaño, no existen rutinas que alteren sus dimensiones de forma directa. Por el contrario, funciones como **`append`**, **`insert`** y **`delete`** generan un arreglo nuevo con una copia de los elementos del arreglo original con la nueva dimensión. Estos son algunos de los métodos usados:

In [159]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
# Función universal para añadir elementos
np.append(arr, 100)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [161]:
# El arreglo original está intacto
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
#Si se desea, se puede reasignar la variable con el nuevo arreglo.
arr = np.append(arr, 11) 

In [163]:
# Eliminar elemento específico
np.delete(arr, 5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [164]:
#Insertar elemento en posición específica
np.insert(arr, 5, 100)

array([  0,   1,   2,   3,   4, 100,   5,   6,   7,   8,   9,  10,  11])

In [165]:
#Crear un arreglo con un nuevo tamaño con el contenido del original
np.resize(arr, (10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11,  0,  1],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3]])

* **Funciones de ordenamiento:** Algunas funciones permiten modificar el orden del contenido del arreglo. Si no es necesario alterar sus dimensiones en el proceso, existen métodos que modifican directamente los elementos. Algunos ejemplos de ordenamiento son:
  * **`np.sort(arr)` | `arr.sort()`**: *NumPy* ofrece las funciones *sort*, que permiten reordenar un arreglo con base a un orden específico, como el alfanumérico para cadenas de texto, o el numérico ascendente y descendente. La diferencia entre la versión de alto nivel y el método de los arreglos es que la función universal crea un nuevo arreglo sin alterar el objeto, y el método realiza el ordenamiento en el sitio, modificando el contenido original.

In [166]:
arr = np.random.randint(0,100, 20)
arr

array([91, 71, 98, 39, 66,  7, 92, 34,  8, 54, 45, 28, 59, 51,  6, 31, 66,
       77, 43, 55])

In [167]:
np.sort(arr)

array([ 6,  7,  8, 28, 31, 34, 39, 43, 45, 51, 54, 55, 59, 66, 66, 71, 77,
       91, 92, 98])

In [168]:
#el arreglo original se ve inalterado
arr

array([91, 71, 98, 39, 66,  7, 92, 34,  8, 54, 45, 28, 59, 51,  6, 31, 66,
       77, 43, 55])

In [169]:
# El método modifica el objeto original
arr.sort()
arr

array([ 6,  7,  8, 28, 31, 34, 39, 43, 45, 51, 54, 55, 59, 66, 66, 71, 77,
       91, 92, 98])

*  **Transformación de forma:** A veces, se quiere construir un arreglo de una forma específica, partiendo de datos previos o generados por funciones como **`np.arange`** o **`np.linspace`**. Algunos de estos son:

  * **`np.reshape(arr, shape)` | `arr.reshape(shape)`**: La función **`reshape`** permite modificar las dimensiones de un arreglo, conservando el contenido y el orden original.

In [170]:
arr = np.arange(36, dtype = 'int')
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [171]:
arr.reshape((6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [172]:
np.reshape(arr, (12,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [173]:
#Ninguno de los dos métodos altera el arreglo original.
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

  * **`np.ravel(arr)` | `arr.flatten()`**: La función **`np.ravel`** y su equivalente para arreglos **`arr.flatten`** genera un arreglo de $1$ dimensión con todo el contenido del arreglo original.

In [174]:
arr = np.random.randint(0, 4, (5,3))
arr

array([[3, 3, 3],
       [3, 2, 0],
       [1, 0, 3],
       [1, 1, 1],
       [3, 1, 1]])

In [175]:
np.ravel(arr)

array([3, 3, 3, 3, 2, 0, 1, 0, 3, 1, 1, 1, 3, 1, 1])

In [176]:
arr.flatten()

array([3, 3, 3, 3, 2, 0, 1, 0, 3, 1, 1, 1, 3, 1, 1])

In [177]:
# Ninguno de los métodos altera el arreglo original
arr

array([[3, 3, 3],
       [3, 2, 0],
       [1, 0, 3],
       [1, 1, 1],
       [3, 1, 1]])

*  **`np.squeeze`**: Compacta las entradas del arreglo para generar un arreglo con menor dimensionalidad. Las dimensiones de tamaño $1$ desaparecen con esta transformación.

In [178]:
arr = np.array([[[0], [1], [2]]])
arr.shape

(1, 3, 1)

In [179]:
arr = np.squeeze(arr)
arr

array([0, 1, 2])

In [180]:
arr.shape

(3,)

### **5.4. Combinación de arreglos**
---

Cuando se trabaja con múltiples arreglos y demás orígenes de datos, suele ser necesario integrarlos en una misma variable para su manejo. Para esto, *NumPy* dispone de algunos métodos para la unión de arreglos.

*  **``np.concatenate((a1,a2,...), axis)``**: Este método permite unir arreglos de manera secuencial en un eje común **`axis`** existente. Para arreglos multidimensionales, el tamaño en cada dimensión debe coincidir, a excepción únicamente del eje indicado para hacer la unión.

In [181]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [182]:
b = np.arange(10, 20).reshape(2,5)
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [183]:
# En el eje 0 (filas)
np.concatenate((a, b), axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [184]:
# En el eje 1 (columnas)
np.concatenate((a, b), axis = 1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [185]:
# Usando multiples valores de entrada.
np.concatenate((a, b, b, a), axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

*  **``np.stack((a1,a2,...), axis)``**: Este método, a diferencia de **`np.concatenate`** permite unir arreglos de manera secuencial en un eje nuevo. De esta manera, los vectores se "apilan" formado matrices, y las matrices formando tensores de $3$ dimensiones. Todos los arreglos pasados como parámetro deben tener la misma forma.

In [186]:
a = np.zeros(5)
b = np.ones(5)

(a.shape, b.shape)

((5,), (5,))

In [187]:
ab = np.stack([a, b, (1,2,3,4,5)]) #Se aceptan colecciones de otros tipos, como listas o tuplas
ab

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 2., 3., 4., 5.]])

In [188]:
#Se crea un nuevo eje al principio al apilar los arreglos.
ab.shape

(3, 5)

In [189]:
a2d = np.eye(3)
b2d = np.zeros((3,3))

{'a': a2d.shape, 'b': b2d.shape}

{'a': (3, 3), 'b': (3, 3)}

In [190]:
#Se crea un arreglo de 3 dimensiones
c3d = np.stack([a2d, b2d])
c3d

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [191]:
c3d.shape

(2, 3, 3)

Existen también 3 funciones de conveniencia usadas para concatenar arreglos en los tres primeros ejes. Estas son:

1. **`np.vstack((a1, a2, ...))`:** Apilar arreglos por el eje vertical (Por filas, axis = 0)
2. **`np.hstack((a1, a2, ...))`:** Apilar arreglos por el eje horizontal (Por columnas, axis = 1)
3. **`np.dstack((a1, a2, ...))`:** Apilar arreglos en orden de profundidad ( axis = 2 )

In [197]:
a = np.random.randint(0, 4, (2,2,2))
a

array([[[3, 3],
        [0, 1]],

       [[0, 2],
        [2, 3]]])

In [198]:
b = np.random.randint(0, 4, (2,2,2))
b

array([[[1, 1],
        [1, 2]],

       [[0, 0],
        [0, 1]]])

In [199]:
# Equivalente a np.concatenate([a, b], 0)
np.vstack([a, b])

array([[[3, 3],
        [0, 1]],

       [[0, 2],
        [2, 3]],

       [[1, 1],
        [1, 2]],

       [[0, 0],
        [0, 1]]])

In [200]:
np.vstack([a, b]).shape

(4, 2, 2)

In [201]:
# Equivalente a np.concatenate([a, b], 1)
np.hstack([a, b])

array([[[3, 3],
        [0, 1],
        [1, 1],
        [1, 2]],

       [[0, 2],
        [2, 3],
        [0, 0],
        [0, 1]]])

In [202]:
np.hstack([a, b]).shape

(2, 4, 2)

In [203]:
# Equivalente a np.concatenate([a, b], 2)
np.dstack([a, b])

array([[[3, 3, 1, 1],
        [0, 1, 1, 2]],

       [[0, 2, 0, 0],
        [2, 3, 0, 1]]])

In [204]:
np.dstack([a, b]).shape

(2, 2, 4)

### **5.5. Separación de arreglos**
---

Eventualmente, también es necesario separar el contenido de un arreglo en subarreglos separados. Tenga en cuenta que esta separación se puede realizar por medio del indexado de arreglos visto en la sección $4$. Sin embargo, esta alternativa es arriesgada por un problema bastante común.  Por ejemplo:

In [205]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Se quiere partir este arreglo a la mitad. Se puede asignar cada mitad a una variable distinta con *slicing*:

In [206]:
izq = arr[:, :2]
izq

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [207]:
der = arr[:, 2:]
der

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.]])

La separación se realizó efectivamente. Sin embargo, si se fuera a modificar el contenido de alguna de las mitades surge un efecto inesperado:

In [208]:
izq[0,1] = 120
izq

array([[  1., 120.],
       [  0.,   1.],
       [  0.,   0.],
       [  0.,   0.]])

Si volvemos a acceder al arreglo original nos daremos cuenta de que su contenido se vio alterado también.

In [209]:
# El arreglo original tiene el mismo cambio del cambio anterior.
arr

array([[  1., 120.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   1.]])

Este problema se podría solucionar empleando **copias** del arreglo original. Esto es posible con el método **`arr.copy()`**.

In [210]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [211]:
copia = arr.copy()
copia[:2, :] = -1
copia

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [212]:
#El arreglo no se altera
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Aún con esta solución, es un proceso bastante largo si se desea hacer una división del arreglo en muchos subarreglos. Para eso, *NumPy* dispone de la familia de métodos **split**. A continuación se discute uno por uno:

*  **`np.split(arr, índices, axis)`:** Este método divide el arreglo en múltiples fragmentos. El argumento **`índices`** puede ser interpretado de dos maneras. 
  * Si es un entero **`n`**, se divide el arreglo en **`n`** partes iguales. Si no se puede dividir el arreglo de esta forma se arroja un error.
  * Si es una lista de enteros, se interpreta como los puntos de corte sobre los que se va a hacer el *slicing*.

In [213]:
arr = np.arange(64).reshape((8,8))

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [214]:
#Por defecto se divide el arreglo por el eje 0 (filas).
np.split(arr, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])]

In [215]:
# Los elementos del arreglo generado son equivalentes a hacer los siguientes slices.
#   arr[:2]
#   arr[2:3]
#   arr[3:6]
#   arr[6:]

np.split(arr, [2, 3, 6])

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]),
 array([[48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])]

In [216]:
np.split(arr, [2,3], axis = 1)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41],
        [48, 49],
        [56, 57]]),
 array([[ 2],
        [10],
        [18],
        [26],
        [34],
        [42],
        [50],
        [58]]),
 array([[ 3,  4,  5,  6,  7],
        [11, 12, 13, 14, 15],
        [19, 20, 21, 22, 23],
        [27, 28, 29, 30, 31],
        [35, 36, 37, 38, 39],
        [43, 44, 45, 46, 47],
        [51, 52, 53, 54, 55],
        [59, 60, 61, 62, 63]])]

*  **`np.array_split(arr, indices, axis)`:** El método **`np.array_split`** es casi idéntico al método **`np.split`**, pero sin retornar error al detectar una división no entera. Cuando esto ocurre, se distribuye de manera casi equivalente. Los primeros arreglos tendrán 1 elemento más, hasta que sea imposible dividir más.

In [217]:
arr = np.arange(7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [218]:
#Se crean 5 arreglos. Dado que solo hay 7 elementos, las primeras 2 filas tendrán 1 más.
np.array_split(arr, 5)

[array([0, 1]), array([2, 3]), array([4]), array([5]), array([6])]

Al igual que con la familia de funciones **`stack`**, *NumPy* dispone de tres funciones de conveniencia para la división de arreglos en los 3 ejes más comunes. Estos son:

1. **`np.vsplit(arr, índices)`:** Divide el arreglo por el eje vertical (Por filas, axis = 0)
2. **`np.hsplit(arr, índices)`:** Divide el arreglo por el eje horizontal (Por columnas, axis = 1)
3. **`np.dsplit(arr, índices)`:** Divide el arreglo en orden de profundidad ( axis = 2 )

In [219]:
arr = np.random.randint(10,100,(2,2,2))
arr

array([[[66, 24],
        [54, 15]],

       [[37, 77],
        [96, 58]]])

In [220]:
vs = np.vsplit(arr, 2)
vs

[array([[[66, 24],
         [54, 15]]]),
 array([[[37, 77],
         [96, 58]]])]

In [221]:
print(vs[0])
print(vs[1])
vs[0].shape

[[[66 24]
  [54 15]]]
[[[37 77]
  [96 58]]]


(1, 2, 2)

In [222]:
hs = np.hsplit(arr, 2)
hs

[array([[[66, 24]],
 
        [[37, 77]]]),
 array([[[54, 15]],
 
        [[96, 58]]])]

In [223]:
print(hs[0])
print(hs[1])
hs[0].shape

[[[66 24]]

 [[37 77]]]
[[[54 15]]

 [[96 58]]]


(2, 1, 2)

In [224]:
ds = np.dsplit(arr, 2)

In [225]:
print(ds[0])
print(ds[1])
ds[0].shape

[[[66]
  [54]]

 [[37]
  [96]]]
[[[24]
  [15]]

 [[77]
  [58]]]


(2, 2, 1)

## **6. Iterando sobre arreglos**
---

No es recomendable iterar un arreglo de *NumPy* a menos de que sea estrictamente necesario. Utilidades como el *broadcasting* y la operación entre arreglos garantizan al usuario operaciones de alto nivel sobre todos los elementos de un arreglo sin la necesidad de iterar sobre ellos. 

Sin embargo, para aquellos casos en los que se requiere realizar una iteración sobre los objetos almacenados en un arreglo de *NumPy* existen algunas funciones que facilitan y optimizan esta tarea.

In [226]:
# Con arreglos de 1-D
arr = np.arange(0,4)
arr

array([0, 1, 2, 3])

In [227]:
# Iterando sobre un arreglo unidimensional
# Esta iteración es trivial, idéntica a la de una lista tradicional
for item in arr:
    print(item)

0
1
2
3


In [228]:
# Con arreglos de 2-D
arr = np.arange(0,4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [229]:
# Al iterar sobre el arreglo, se accede a cada fila.
for fila in arr:
    print(fila)

[0 1]
[2 3]


In [230]:
# Si se quiere hacer una operación sobre cada uno de los valores, se puede usar la propiedad "flat"
# también se pueden usar los métodos ravel y flatten vistos anteriormente
for item in arr.flat:
    print(item)

0
1
2
3


Otra forma recomendada es con el método **`np.nditer(arr)`**:

In [231]:
for item in np.nditer(arr):
    print(item)

0
1
2
3


Este método también permite iterar en cada pareja posible entre los elementos de múltiples arreglos utilizando el *broadcasting*.

In [232]:
arr = [np.arange(4), np.eye(4, dtype = int)]
for i,j in np.nditer(arr):
    print(f'{i},{j}')

0,1
1,0
2,0
3,0
0,0
1,1
2,0
3,0
0,0
1,0
2,1
3,0
0,0
1,0
2,0
3,1


Otro método importante en la iteración de arreglos de *NumPy* es el método **`np.ndenumerate(arr)`** que, similar al método **`np.nditer(arr)`**, crea un iterador sobre los elementos del arreglo, pero adicionalmente itera sobre la posición de cada elemento en forma de tupla.

In [233]:
# Iterar sobre el par de coordenadas x,y
arr = np.array([[1,2],[3,4],[5,6]])

print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [234]:
for (i, j), value in np.ndenumerate(arr):
  print('Fila:', i, 'Col:', j, 'Valor:', value)

Fila: 0 Col: 0 Valor: 1
Fila: 0 Col: 1 Valor: 2
Fila: 1 Col: 0 Valor: 3
Fila: 1 Col: 1 Valor: 4
Fila: 2 Col: 0 Valor: 5
Fila: 2 Col: 1 Valor: 6


## **Recursos adicionales**
---

En este material se consideran algunas de las funciones más comunes, pero quedan otras por fuera del alcance. Lo invitamos a que consulte la [documentación oficial](https://numpy.org/doc/stable/reference/index.html), o librerías similares del ámbito científico como [*SciPy*](https://docs.scipy.org/doc/scipy/reference/) en busca de funciones que se ajusten a las necesidades de su problema. De igual forma, a continuación se presenta una lista de recursos adicionales que le serán de utilidad:

*  [NumPy Home page](https://numpy.org/)
*  [NumPy Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html)
*  [NumPy: the absolute basics for beginners](https://numpy.org/devdocs/user/absolute_beginners.html)
*  [tutorialspoint - NumPy Tutorial](https://www.tutorialspoint.com/numpy/index.htm)
*  [Oliphant, T.E. (2006). Guide to NumPy](http://web.mit.edu/dvp/Public/numpybook.pdf)
*  [StackOverflow - What are the advantages of NumPy over regular Python lists?](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists)
*  [Standard Statistical Distributions (e.g. Normal, Poisson, Binomial) and their uses](https://www.healthknowledge.org.uk/public-health-textbook/research-methods/1b-statistical-methods/statistical-distributions)
